// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfmwdryfbpfopmebtlro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbXdkcnlmYnBmb3BtZWJ0bHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODYwODksImV4cCI6MjA3NDM2MjA4OX0.aWUGsdelBFW8A8PigpDmQ-Yev_KE-84rqtUlWvQjqvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});